Update org-mpv-notes.el
bpanthi977/org-mpv-notes pull request #27
Opened 2024-11-15 11:01 UTC by cnoceda

fixed org-mpv-notes--ocr-on-file to support org-mpv-notes-ocr-command-args as string.

2024-11-15 11:01 UTC, cnoceda commented
Solution to the issue #26

2024-11-15 11:10 UTC, cnoceda commented
Sorry I miss a parenthesis.

2024-11-15 11:17 UTC, cnoceda commented
Keep in mind that its my first contribution, so it could be not as good as needed. :-) My apologies.

2024-11-16 22:21 UTC, bpanthi977 requested changes
Thanks for the contribution. Your code is correct. However a few modifications could be made.

`apply` treats it last argument as a list of arguments to call the function with. So append is not necessary. i.e. the following works:
```elisp
(apply #'call-process ... (split-string-shell-command org-mpv-notes-ocr-command-args))
```

Also note that I used `#'call-process` instead of `'call-process`. Both are correct however I prefer `#'call-process`. Mainly because, I am influenced by Common Lisp and `#'` gives the meaning that `call-process` is a function.

2024-11-19 16:27 UTC, merged